export const posts = [
    {
      id: 1,
      author: { name: "Jane Smith", username: "@janesmith", initials: "JS" },
      content: "Just finished building my first full-stack app with Next.js and Prisma. The developer experience is incredible! 🚀",
      timestamp: "2 hours ago",
      likes: 24,
      comments: 5,
      isLiked: false,
      isBookmarked: false,
    },
    {
      id: 2,
      author: { name: "Alex Chen", username: "@alexchen", initials: "AC" },
      content: "Hot take: TypeScript is not optional anymore. It's a must-have for any serious project. Type safety saves hours of debugging.",
      timestamp: "4 hours ago",
      likes: 156,
      comments: 42,
      isLiked: true,
      isBookmarked: true,
    },
    {
      id: 3,
      author: { name: "Sarah Wilson", username: "@sarahw", initials: "SW" },
      content: "Working on authentication with Auth.js. The new v5 is so much cleaner. Anyone else migrating from NextAuth v4?",
      timestamp: "6 hours ago",
      likes: 89,
      comments: 23,
      isLiked: false,
      isBookmarked: false,
    },
    {
      id: 4,
      author: { name: "Mike Johnson", username: "@mikej", initials: "MJ" },
      content: "Database design tip: Always think about your queries before designing your schema. Learned this the hard way with Neon + Prisma.",
      timestamp: "8 hours ago",
      likes: 234,
      comments: 67,
      isLiked: true,
      isBookmarked: false,
    },
    {
      id: 5,
      author: { name: "Emily Davis", username: "@emilyd", initials: "ED" },
      content: "Finally understood bcrypt and password hashing. Security is no joke. Never store plain text passwords! 🔐",
      timestamp: "1 day ago",
      likes: 312,
      comments: 45,
      isLiked: false,
      isBookmarked: true,
    },
  ];
