export const posts = [
    {
      id: 1,
      author: { name: "Jane Smith", username: "@janesmith", initials: "JS" },
      content: "Just finished building my first full-stack app with Next.js and Prisma. The developer experience is incredible! 🚀",
      timestamp: "2 hours ago",
      likes: 24,
      comments: 5,
      isLiked: false,
      isBookmarked: false,
    },
    {
      id: 2,
      author: { name: "Alex Chen", username: "@alexchen", initials: "AC" },
      content: "Hot take: TypeScript is not optional anymore. It's a must-have for any serious project. Type safety saves hours of debugging.",
      timestamp: "4 hours ago",
      likes: 156,
      comments: 42,
      isLiked: true,
      isBookmarked: true,
    },
    {
      id: 3,
      author: { name: "Sarah Wilson", username: "@sarahw", initials: "SW" },
      content: "Working on authentication with Auth.js. The new v5 is so much cleaner. Anyone else migrating from NextAuth v4?",
      timestamp: "6 hours ago",
      likes: 89,
      comments: 23,
      isLiked: false,
      isBookmarked: false,
    },
    {
      id: 4,
      author: { name: "Mike Johnson", username: "@mikej", initials: "MJ" },
      content: "Database design tip: Always think about your queries before designing your schema. Learned this the hard way with Neon + Prisma.",
      timestamp: "8 hours ago",
      likes: 234,
      comments: 67,
      isLiked: true,
      isBookmarked: false,
    },
    {
      id: 5,
      author: { name: "Emily Davis", username: "@emilyd", initials: "ED" },
      content: "Finally understood bcrypt and password hashing. Security is no joke. Never store plain text passwords! 🔐",
      timestamp: "1 day ago",
      likes: 312,
      comments: 45,
      isLiked: false,
      isBookmarked: true,
    },
    {
      id: 6,
      author: { name: "Michael Chen", username: "@mikecodes", initials: "MC" },
      content: "React state finally clicked today. Lifting state up is powerful once it makes sense.",
      timestamp: "2 days ago",
      likes: 198,
      comments: 22,
      isLiked: true,
      isBookmarked: false,
    },
    {
      id: 7,
      author: { name: "Sophia Martinez", username: "@sophiadev", initials: "SM" },
      content: "Tailwind CSS is basically LEGO for UI. Once you get it, you can build anything fast.",
      timestamp: "3 days ago",
      likes: 421,
      comments: 61,
      isLiked: false,
      isBookmarked: false,
    },
    {
      id: 8,
      author: { name: "Daniel Okoro", username: "@danbuilds", initials: "DO" },
      content: "Finally deployed my first fullstack app. Backend + DB + frontend all working 🎉",
      timestamp: "5 hours ago",
      likes: 540,
      comments: 88,
      isLiked: true,
      isBookmarked: true,
    },
    {
      id: 9,
      author: { name: "Aisha Khan", username: "@aishacodes", initials: "AK" },
      content: "Async/await > callbacks. My brain thanks JavaScript evolution.",
      timestamp: "6 hours ago",
      likes: 267,
      comments: 34,
      isLiked: false,
      isBookmarked: false,
    },
    {
      id: 10,
      author: { name: "Liam Johnson", username: "@liamdev", initials: "LJ" },
      content: "Learning Git deeply changed how I work. Branching is underrated.",
      timestamp: "1 week ago",
      likes: 389,
      comments: 40,
      isLiked: true,
      isBookmarked: false,
    },
    {
      id: 11,
      author: { name: "Grace Lee", username: "@gracecodes", initials: "GL" },
      content: "Finally understand REST vs GraphQL. Both have their place.",
      timestamp: "2 hours ago",
      likes: 153,
      comments: 12,
      isLiked: false,
      isBookmarked: true,
    },
    {
      id: 12,
      author: { name: "Noah Williams", username: "@noahbuilds", initials: "NW" },
      content: "Debugging > Coding. Half my time is just detective work 🕵️‍♂️",
      timestamp: "8 hours ago",
      likes: 302,
      comments: 28,
      isLiked: true,
      isBookmarked: false,
    },
    {
      id: 13,
      author: { name: "Chloe Brown", username: "@chloetech", initials: "CB" },
      content: "CSS grid saved my layout today. Flexbox couldn't do it alone.",
      timestamp: "4 days ago",
      likes: 211,
      comments: 19,
      isLiked: false,
      isBookmarked: false,
    },
    {
      id: 14,
      author: { name: "Ethan Wilson", username: "@ethancode", initials: "EW" },
      content: "Understanding closures felt like unlocking a secret JavaScript level.",
      timestamp: "2 days ago",
      likes: 477,
      comments: 56,
      isLiked: true,
      isBookmarked: true,
    },
    {
      id: 15,
      author: { name: "Maya Patel", username: "@mayadev", initials: "MP" },
      content: "Built my first API with Express today. Routes finally make sense!",
      timestamp: "10 hours ago",
      likes: 188,
      comments: 17,
      isLiked: false,
      isBookmarked: false,
    },
    {
      id: 16,
      author: { name: "Lucas Silva", username: "@lucasjs", initials: "LS" },
      content: "TypeScript errors are annoying until they save you from a bug 😅",
      timestamp: "3 days ago",
      likes: 356,
      comments: 44,
      isLiked: true,
      isBookmarked: false,
    },
    {
      id: 17,
      author: { name: "Zara Ahmed", username: "@zara.dev", initials: "ZA" },
      content: "Dark mode toggle added. Productivity instantly +20%.",
      timestamp: "12 hours ago",
      likes: 290,
      comments: 31,
      isLiked: false,
      isBookmarked: true,
    },
    {
      id: 18,
      author: { name: "Henry Walker", username: "@henrycodes", initials: "HW" },
      content: "Next.js routing is so clean. File-based routing just feels right.",
      timestamp: "1 day ago",
      likes: 501,
      comments: 70,
      isLiked: true,
      isBookmarked: false,
    },
    {
      id: 19,
      author: { name: "Isabella Rossi", username: "@isarossi", initials: "IR" },
      content: "Spent 2 hours fixing a typo. Humbling experience.",
      timestamp: "7 hours ago",
      likes: 612,
      comments: 102,
      isLiked: true,
      isBookmarked: true,
    },
    {
      id: 20,
      author: { name: "David Kim", username: "@dkbuilds", initials: "DK" },
      content: "Learning Docker now. Containers make deployment less scary.",
      timestamp: "2 weeks ago",
      likes: 174,
      comments: 15,
      isLiked: false,
      isBookmarked: false,
    },
    {
      id: 21,
      author: { name: "Fatima Bello", username: "@fatimadev", initials: "FB" },
      content: "Finally comfortable with MongoDB queries. NoSQL isn't so scary anymore.",
      timestamp: "9 hours ago",
      likes: 245,
      comments: 29,
      isLiked: true,
      isBookmarked: false,
    },
    {
      id: 22,
      author: { name: "Oliver Scott", username: "@oscott", initials: "OS" },
      content: "Animations with Framer Motion make UI feel alive ✨",
      timestamp: "3 hours ago",
      likes: 329,
      comments: 26,
      isLiked: false,
      isBookmarked: true,
    },
    {
      id: 23,
      author: { name: "Hannah Müller", username: "@hannahcodes", initials: "HM" },
      content: "Code reviews teach you more than tutorials ever will.",
      timestamp: "6 days ago",
      likes: 410,
      comments: 52,
      isLiked: true,
      isBookmarked: false,
    },
    {
      id: 24,
      author: { name: "Samuel Green", username: "@samdev", initials: "SG" },
      content: "Understanding event loop = JavaScript enlightenment moment.",
      timestamp: "11 hours ago",
      likes: 372,
      comments: 41,
      isLiked: false,
      isBookmarked: false,
    },
    {
      id: 25,
      author: { name: "Nina Petrova", username: "@ninacodes", initials: "NP" },
      content: "Finally using environment variables properly. No more secrets in code 🙌",
      timestamp: "1 day ago",
      likes: 288,
      comments: 23,
      isLiked: true,
      isBookmarked: true,
    }
];
